name: Create and publish a Docker image

on:
  push:
    branches: ['master']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build webpack
        working-directory: ./client
        run: |
          npm install
          npm run build
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "rock-paper-scissors-rt"
          heroku_email: "saphidev@gmail.com"