name: Create and publish a Docker image

on:
  push:
    branches: ['release']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build webpack
        working-directory: ./client
        run: |
          npm install
          npm run build